name: bash-get-curl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    
    steps:
      - uses: actions/checkout@v3

      - name: BashOneLiner
        run: echo Hello, world!

      - name: Bash multi line
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Get runner IP
        run: |
          echo Get me this runner IP 
          curl -s https://ifconfig.me/

      - name: List commands
        run: |
          apropos -s 1 ''

#       - name: Use secrets
#         run: |
#           echo ${{ secrets.REPO_SECRET }} > somefile.txt
#           echo ${{ secrets.REPO_SECRET }}
#           pwd
#           cat somefile.txt

      - name: Use secrets and variables
        run: |
          echo ${{ secrets.REPO_SECRET }} > somefile.txt
          echo $ENV_VAR >> somefile.txt
          pwd
          cat somefile.txt
