name: bash-get-curl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        mxver: ["first", "second"]
        include:
          - mxver: "first"
            npm: "yes"
          - mxver: "third"

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

#       - name: Get runner IP
#         run: |
#           echo Get me this runner IP 
#           curl -s https://ifconfig.me/

#       - name: List commands
#         run: |
#           apropos -s 1 ''

      - name: Use secrets and variables
        run: |
          echo ${{ matrix.mxver }}

      - name: Only if first matrix run
        if: ${{ matrix.npm }}
        run: |
          echo NPM is ${{ matrix.npm }}

  request:
    runs-on: ubuntu-latest
    needs: build
    environment: Staging
    env:
      ENVIRO1: ${{ vars.ENV_VAR }}
    
    steps:
      - name: Use variables
        run: |
          echo "$ENVIRO1" > somefile.txt
          echo "${{ vars.ENV_VAR }}" > somefile.txt
          cat somefile.txt

      - name: AzCLI
        run: |
          az -v
